### ISSUE TITLE
Implement workaround for registering Docker Services with correct IP

### ISSUE THREAD

**Issue by daves125125** [opinari/onthefence-service-registry#16]
Registrator has a set of compatibility issues with Docker Swarm 12.x and Services in general, i.e:

(Docker Service port exposure):
-https://github.com/gliderlabs/registrator/issues/443

(-ip and -internal incompatibility):
-https://github.com/gliderlabs/registrator/issues/495

In short, we need to find a way to register (preferably using Registrator) a Docker service into Consul with the correct IP (preferably a docker private network IP OR a DO private networking IP) to allow other services to lookup entries from Consul and perform Health checks.

**Comment by daves125125** [comment]
Used Docker Swarm mode IPs only - health checks coming in 1.13

**Comment by slawekgh** [comment]
It is possible - In my Infra it is  running perfectly 

All services are started by Swarm but haproxy takes config from consul where registrators send info about running containers 

You need to run registrator with options internal + cleanup + resync 

And of course haproxy as a swarm service to be in the same private overlay network than business services from swarm
